import type { Property } from "@/lib/types";
import { propertyImage } from "@/lib/images";

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "1",
    title: "פנטהאוז מרהיב עם נוף לים",
    description:
      "דירת פנטהאוז יוקרתית עם מרפסת ענקית, ממ״ד וחניה כפולה במרינה אשדוד. נוף פנורמי לים, מפרט גבוה ומעלית שבת.",
    listingType: "buy",
    city: "ashdod",
    neighborhood: "מרינה",
    price: 4200000,
    rooms: 5,
    area: 180,
    floor: 12,
    totalFloors: 12,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(0),
    featured: true,
  },
  {
    id: "2",
    title: "דירת גן מעוצבת ביבנה",
    description:
      "דירת 4 חדרים עם גינה פרטית, מטבח פתוח ומפרט פרימיום. שכונה שקטה ומשפחתית, קרובה לבתי ספר ופארקים.",
    listingType: "buy",
    city: "yavne",
    neighborhood: "נאות שקד",
    price: 2850000,
    rooms: 4,
    area: 120,
    floor: 0,
    totalFloors: 4,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(1),
    featured: true,
  },
  {
    id: "3",
    title: "דירה להשכרה ליד הים",
    description:
      "דירת 3 חדרים מרוהטת במרינה אשקלון, זמינה מיידית. מרחק הליכה לחוף, מזגן בכל החדרים.",
    listingType: "rent",
    city: "ashkelon",
    neighborhood: "מרינה",
    price: 7500,
    rooms: 3,
    area: 85,
    floor: 5,
    totalFloors: 8,
    mamad: true,
    balcony: true,
    parking: false,
    image: propertyImage(2),
  },
  {
    id: "4",
    title: "דופלקס חדש בגן יבנה",
    description:
      "דופלקס 5 חדרים בפרויקט חדש, מפרט גבוה ומעלית. מרפסת שמש גדולה וחניה כפולה.",
    listingType: "buy",
    city: "gan-yavne",
    neighborhood: "נאות הדר",
    price: 3100000,
    rooms: 5,
    area: 145,
    floor: 3,
    totalFloors: 4,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(3),
  },
  {
    id: "5",
    title: "דירת 3 חדרים ברובע י\"א",
    description:
      "דירה משופצת, קרובה לים ולמרכזי קניות. מטבח חדש, ריצוף פרקט וממ״ד.",
    listingType: "rent",
    city: "ashdod",
    neighborhood: "רובע י\"א",
    price: 5800,
    rooms: 3,
    area: 78,
    floor: 4,
    totalFloors: 9,
    mamad: false,
    balcony: true,
    parking: true,
    image: propertyImage(4),
  },
  {
    id: "6",
    title: "וילה יוקרתית באשקלון",
    description:
      "וילה פרטית עם בריכה, גינה מטופחת ו-6 חדרים. עיצוב אדריכלי ייחודי ופרטיות מלאה.",
    listingType: "buy",
    city: "ashkelon",
    neighborhood: "ברנע",
    price: 6500000,
    rooms: 6,
    area: 280,
    floor: 0,
    totalFloors: 2,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(5),
    featured: true,
  },
  {
    id: "7",
    title: "דירת 4 חדרים בנאות שז״ר",
    description:
      "דירה מרווחת בקומה גבוהה עם נוף פתוח, ממ״ד וחניה. בניין עם לובי מפואר.",
    listingType: "buy",
    city: "yavne",
    neighborhood: "נאות שז\"ר",
    price: 2450000,
    rooms: 4,
    area: 110,
    floor: 7,
    totalFloors: 10,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(6),
  },
  {
    id: "8",
    title: "סטודיו מעוצב במרינה",
    description:
      "סטודיו מרוהט להשכרה לטווח ארוך, מרחק הליכה מהים. מתאים ליחידים או זוגות.",
    listingType: "rent",
    city: "ashdod",
    neighborhood: "מרינה",
    price: 4200,
    rooms: 1,
    area: 42,
    floor: 3,
    totalFloors: 6,
    mamad: false,
    balcony: true,
    parking: false,
    image: propertyImage(7),
  },
  {
    id: "9",
    title: "דירת 5 חדרים בגבעת וינגייט",
    description:
      "דירת קרקע עם גינה פרטית, מתאימה למשפחות. שכונה ירוקה ושקטה.",
    listingType: "buy",
    city: "ashkelon",
    neighborhood: "גבעת וינגייט",
    price: 3800000,
    rooms: 5,
    area: 155,
    floor: 0,
    totalFloors: 2,
    mamad: true,
    balcony: true,
    parking: true,
    image: propertyImage(8),
  },
];

export function getPropertyById(id: string): Property | undefined {
  return MOCK_PROPERTIES.find((p) => p.id === id);
}
