import type { ManagedProperty } from "./types";

export const INITIAL_MANAGED_PROPERTIES: ManagedProperty[] = [
  {
    id: "mp_001",
    district: "מרינה",
    street: "הרצל",
    houseNumber: "12",
    rooms: 5,
    floor: 11,
    totalFloors: 12,
    elevator: true,
    parking: true,
    mamad: true,
    askingPrice: 4200000,
    status: "exclusive",
    recruitedAt: "2026-05-12T09:00:00.000Z",
    agentId: "usr_elina_bayder",
    agentEmail: "elina.bayder@rehouse.co.il",
    agentName: "אלינה ביידר",
    media: {
      imageNames: ["marina-penthouse-1.jpg", "marina-penthouse-2.jpg"],
      videoUrl: "",
      matterportUrl: "https://my.matterport.com/show/?m=example-marina",
    },
  },
  {
    id: "mp_002",
    district: "רובע י׳",
    street: "בן גוריון",
    houseNumber: "45",
    rooms: 3,
    floor: 4,
    totalFloors: 9,
    elevator: true,
    parking: true,
    mamad: false,
    askingPrice: 1850000,
    status: "active",
    recruitedAt: "2026-05-28T14:30:00.000Z",
    agentId: "usr_pavel_kachka",
    agentEmail: "pavel.kachka@rehouse.co.il",
    agentName: "פבל קצ׳קה",
    media: {
      imageNames: ["yud-street-apt.jpg"],
      videoUrl: "",
      matterportUrl: "",
    },
  },
  {
    id: "mp_003",
    district: "רובע סיטי הקרייה",
    street: "העצמאות",
    houseNumber: "8",
    rooms: 4,
    floor: 7,
    totalFloors: 18,
    elevator: true,
    parking: true,
    mamad: true,
    askingPrice: 2650000,
    status: "active",
    recruitedAt: "2026-06-01T11:15:00.000Z",
    agentId: "usr_igor_hanin",
    agentEmail: "igor.hanin@rehouse.co.il",
    agentName: "איגור חנין",
    media: {
      imageNames: ["city-tower-living.jpg", "city-tower-view.jpg"],
      videoUrl: "https://example.com/city-tour.mp4",
      matterportUrl: "",
    },
  },
  {
    id: "mp_004",
    district: "מע״ר דרום",
    street: "שדרות מנחם בגין",
    houseNumber: "102",
    rooms: 2,
    floor: 2,
    totalFloors: 6,
    elevator: false,
    parking: false,
    mamad: true,
    askingPrice: 1420000,
    status: "frozen",
    recruitedAt: "2026-06-10T08:45:00.000Z",
    agentId: "usr_yonatan_buzaglo",
    agentEmail: "yonatan.buzaglo@rehouse.co.il",
    agentName: "יונתן בוזגלו",
    media: {
      imageNames: [],
      videoUrl: "",
      matterportUrl: "",
    },
  },
];
